language: python
python:
    - "2.7"
    - "3.6"
cache: apt
before_install:
    - sudo apt-get -qq  update -y
    - pip -q install 'pytest>=3.6.0'
    - pip -q install pytest-cov codecov coveralls

install:
    - pip install -r requirements.txt

script:
    - py.test --cov=dsptools tests/

after_success:
    - codecov
    - coveralls
